---
# tasks file for docker bench
- name: checkout docker bench git repo
  git: 
    repo: https://github.com/docker/docker-bench-security.git
    dest: /opt/dockerbench
    accept_hostkey: true

- name: run docker bench script
  shell: set -x | sh docker-bench-security.sh
  sudo: yes
  args:
    chdir: /opt/dockerbench
