---
# tasks file for docker bench
- name: run dockerbench container
  docker:
    name: dockerbench
    image: "{{ dockerbench_image }}"
    state: started
    command: "exit $?"
    restart_policy: always
    net: host
    pid: host
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    - "/usr/lib/systemd:/usr/lib/systemd"
    - "/etc:/etc"
  environment: proxy_env
  when: dockerbench_run_test
  tags:
    - dockerbench
